### ISSUE TITLE
Documentation of what appears in Cheat Sheet

### ISSUE THREAD

**Issue by julianstirling** [revarbat/openscad_docsgen#11]
I generate an empty cheat sheet at the moment. From the docs I can't see what should go into the cheat sheet. I think, looking at the code, it is only functions from prioritized files? Is this correct? Can the explanation be added to the documentation?

**Comment by revarbat** [comment]
Sorry.  The CheatSheet is built up from all the `Usage:` lines for each module, function, and the names of each constant.
I'll add this into the docs.
