### ISSUE TITLE
underscores are escaped in usage

### ISSUE THREAD

**Issue by julianstirling** [revarbat/openscad_docsgen#16]
**This:**

![image](https://user-images.githubusercontent.com/12807051/169357261-0ff00057-5a84-4bb1-80e1-01942c0e8699.png)

**Generates:**

![image](https://user-images.githubusercontent.com/12807051/169357206-dce5b1d7-d27d-476d-944e-28b323b89789.png)

**Comment by revarbat** [comment]
This does not appear to still be the case.
