### ISSUE TITLE
Consider renaming Index.md

### ISSUE THREAD

**Issue by julianstirling** [revarbat/openscad_docsgen#17]
When generating for a website that isn't a wiki `Index.md` will become `Index.html`. The root page of the website must be `index.md` which is only a different by the case of the filename. I would be possible to have both `index.html` and `Index.html`, this is a bit confusing and this would fail on operating systems where filenames are case independent.

**Comment by revarbat** [comment]
Index.md does not have to be named that, as it is just an alphabetic index of functions and modules.
It should be fine if I change the filename to something like Alphabetic-Index.md

**Comment by revarbat** [comment]
Release v2.0.33 changes Index.md to AlphaIndex.md
