### ISSUE TITLE
Integration/output for SCA2D

### ISSUE THREAD

**Issue by julianstirling** [revarbat/openscad_docsgen#8]
This may take some discussion. I am writing [SCA2D](https://gitlab.com/bath_open_instrumentation_group/sca2d) which is a linter or static code analyser for OpenSCAD.

One thing I want to do is warn when people have not documented their functions and modules. Sort of like PyLint does for python. I was about to define my own doc string format when I cam across `openscad_docsgen`. It make sense for sca2d to use your standard as it already exists, and creates great documentation.

As SCA2D is also in python, I think that the most sensible way for SCA2D to check docstrings would be to run `openscad_docsgen`. This way I know exactly what documentation `openscad_docsgen` has found without having to reimplement anything.

To do this I would probably need a function that returns all of the block information as something like a dictionary, but that also returns the line numbers the blocks were read from. With this information I should be able to check that the function is documented directly before implementation and that the arguments match, etc.

I am not proposing that you do these changes. I am just checking that you would be happy for me to put the time in to make them?

**Comment by revarbat** [comment]
This shouldn't be hard to implement.

**Comment by revarbat** [comment]
I implemented a couple interfaces to do this in commit 45bfb60d82e9e1f89c21cf4f95780b96d7642919 .
Check the README for an example of using them, and the expected returned data format.
